DROP DATABASE IF EXISTS XPInc;

CREATE DATABASE XPInc;

CREATE TABLE XPInc.clients(
  idClient INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(50) NOT NULL,
  
  CONSTRAINT PRIMARY KEY(idClient)

) ENGINE = INNODB;

CREATE TABLE XPInc.wallets(
  idWallet INT NOT NULL AUTO_INCREMENT,
  idClient INT NOT NULL,
  balance DECIMAL(65,2) NOT NULL DEFAULT(0.00),

  CONSTRAINT PRIMARY KEY(idWallet),
  FOREIGN KEY(idClient) REFERENCES clients(idClient)

) ENGINE = INNODB;

CREATE TABLE XPInc.wallet_history(
  idWH INT NOT NULL AUTO_INCREMENT,
  idWallet INT NOT NULL,
  operation VARCHAR(50) NOT NULL,
  value DECIMAL(65,2) NOT NULL,
  createdAt DATETIME DEFAULT (CURRENT_TIMESTAMP),

  CONSTRAINT PRIMARY KEY( idWH),
  FOREIGN KEY(idWallet) REFERENCES wallets(idWallet)

) ENGINE = INNODB;

CREATE TABLE XPInc.assets(
  idAsset INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  qtde INT NOT NULL,
  value DECIMAL(65,2) NOT NULL, 

  CONSTRAINT PRIMARY KEY(idAsset)

) ENGINE = INNODB;

CREATE TABLE XPInc.client_assets(
  idCA INT NOT NULL AUTO_INCREMENT,
  idWallet INT NOT NULL,
  idAsset INT NOT NULL DEFAULT(0),
  qtde INT NOT NULL  DEFAULT(0),

  CONSTRAINT PRIMARY KEY(idCA),
  FOREIGN KEY(idWallet) REFERENCES wallets(idWallet),
  FOREIGN KEY(idAsset) REFERENCES assets(idAsset)

) ENGINE = INNODB;

CREATE TABLE XPInc.assets_history(
  idAH INT NOT NULL AUTO_INCREMENT,
  idWallet INT NOT NULL,
  idAsset INT NOT NULL,
  operation VARCHAR(50),
  qtde INT NOT NULL,
  value DECIMAL(65,2) NOT NULL DEFAULT(0),

  CONSTRAINT PRIMARY KEY(idAH),
  FOREIGN KEY(idWallet) REFERENCES wallets(idWallet),
  FOREIGN KEY(idAsset) REFERENCES assets(idAsset)

) ENGINE = INNODB;

INSERT INTO XPInc.assets (name, qtde, value) VALUES
("AZUL4", 10000, 350),
("PETR4", 10000, 350),
("VALE4", 10000, 350),
("XPTO", 10000, 350);

